import { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation and premium sound quality.',
    price: 299.99,
    originalPrice: 399.99,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Electronics',
    rating: 4.8,
    reviews: 1247,
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Smart Fitness Watch',
    description: 'Advanced fitness tracking with heart rate monitoring and GPS functionality.',
    price: 249.99,
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Electronics',
    rating: 4.6,
    reviews: 892,
    inStock: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Designer Leather Backpack',
    description: 'Premium leather backpack perfect for work and travel with multiple compartments.',
    price: 159.99,
    originalPrice: 199.99,
    image: 'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Fashion',
    rating: 4.7,
    reviews: 634,
    inStock: true,
    featured: false,
  },
  {
    id: '4',
    name: 'Minimalist Desk Lamp',
    description: 'Modern LED desk lamp with adjustable brightness and USB charging port.',
    price: 79.99,
    image: 'https://images.pexels.com/photos/1129413/pexels-photo-1129413.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Home',
    rating: 4.5,
    reviews: 423,
    inStock: true,
    featured: false,
  },
  {
    id: '5',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
    price: 39.99,
    originalPrice: 59.99,
    image: 'https://images.pexels.com/photos/4316739/pexels-photo-4316739.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Electronics',
    rating: 4.4,
    reviews: 756,
    inStock: true,
    featured: true,
  },
  {
    id: '6',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable organic cotton t-shirt available in multiple colors.',
    price: 29.99,
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Fashion',
    rating: 4.3,
    reviews: 1123,
    inStock: true,
    featured: false,
  },
  {
    id: '7',
    name: 'Stainless Steel Water Bottle',
    description: 'Insulated stainless steel water bottle that keeps drinks cold for 24 hours.',
    price: 34.99,
    image: 'https://images.pexels.com/photos/7262901/pexels-photo-7262901.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Lifestyle',
    rating: 4.6,
    reviews: 887,
    inStock: true,
    featured: false,
  },
  {
    id: '8',
    name: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker with 360-degree sound and waterproof design.',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Electronics',
    rating: 4.7,
    reviews: 1456,
    inStock: true,
    featured: true,
  },
];

export const categories = [
  'All',
  'Electronics',
  'Fashion',
  'Home',
  'Lifestyle',
];